### ISSUE TITLE
Package nodrew/php-airbrake is abandoned, you should avoid using it. Use dbtlr/php-airbrake instead.

### ISSUE THREAD

**Issue by mseshachalam** [dbtlr/PhpAirbrakeBundle#11]
When will the bundle start using dbtlr/php-airbrake ?

**Comment by dbtlr** [comment]
Sorry, it has been a couple of years since I've used this code. I can definitely update, but this bundle is way out of date. I'll take a look and see if there is anything else that needs to be done as well.

**Comment by dbtlr** [comment]
I merged your pull request, as it looks like the modifications I've made to the airbrake package don't negatively affect the bundle.
